version: '3.4'

services:
  ultrabank-wallet:
    image: ${DOCKER_REGISTRY-}ultrabankwallet
    build:
      context: .
      dockerfile: UltraBank-Wallet/Dockerfile

  ultra-bank-frontend:
    image: ultra-bank-frontend
    build:
      context: ../../UltraBank-Frontend
      dockerfile: ./Dockerfile