version: '3.4'

services:
  nginx:
    ports:
      - "80:80"
    volumes:
      - '../../nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - ultrabank-wallet
      - ultra-bank-frontend

  ultrabank-wallet:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  ultra-bank-frontend:
    ports:
      - "3000"